#Configuration
server:
  port: 8080

#H2 (testdb, sa) jdbcTemplate과 함께 쓰면 유용!
spring:
  h2:
    console:
      enabled: true
#MySQL 설정
# spring:
#     datasource:
#         url: jdbc:mysql://[AWS 주소]:3306/[database명]?allowPublicKeyRetrieval=true&useSSL=false
#         username: username
#         password: pwd
