#Configuration
server:
  port: 8080

spring:
  application :
    name : chatbot_spring

#H2 (testdb, sa) jdbcTemplate과 함께 쓰면 유용!
  h2:
    console:
      enabled: true
  kafka:
      consumer :
        bootstrap-servers: ec2-13-209-19-186.ap-northeast-2.compute.amazonaws.com:9092
        group-id: chatbotGroup
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      producer:
        bootstrap-servers: ec2-13-209-19-186.ap-northeast-2.compute.amazonaws.com:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

  #MySQL 설정
  # datasource:
  #   url: jdbc:mysql://mariadbportfolio.cua32mtg2la4.ap-northeast-2.rds.amazonaws.com:3306/portfolio?allowPublicKeyRetrieval=true&useSSL=false
  #   username: admin
  #   password: rootroot